### ISSUE TITLE
How the overlaying of the two images is performed?

### ISSUE THREAD

**Issue by empet** [koldunovn/FESOM_SST_shaded_by_U#2]
Thank you for posting this notebook.  I'd like to know however what happens behind the scenes.
More precisely, when we call `imshow` for the same `ax`, as in your code:
```
ax.imshow(np.flipud(sst.sst.values), cmap=cm.RdBu_r,  vmin=12, vmax=24)
ax.imshow(np.flipud(u.u_surf.values), alpha=0.3, cmap=cm.gray, vmin=-.3, vmax=0.3)
```
how the overlaying of the two images is performed? What mathematical operations are involved to create a layered image? I'd be greatful for a link to the theoretical support of this operation.

**Comment by koldunovn** [comment]
You should probably ask matplotlib folks, I don't know the details of their implementation, sorry.

**Comment by empet** [comment]
Thank you!!!

**Comment by trackow** [comment]
My understanding was always that this is just a simple ["alpha composite"](https://en.wikipedia.org/wiki/Alpha_compositing). The first imshow creates an image _a_, and the second image _b_ is combined with the first one (accounting for alpha=0.3) as follows to generate image _o_:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/26135424/118359250-efe3ed00-b582-11eb-93f8-86eb47700fe5.png">

```
Here C_{o}, C_{a} and C_{b} stand for the color components of the pixels in the result, image a and image b respectively, applied to each color channel (red/green/blue) individually, whereas 
α_{o}, α_{a} and α_{b} are the alpha values of the respective pixels.
```

As Nikolay said, not sure whether this is exactly how it is implemented in matplotlib.

**Comment by empet** [comment]
Thank you very much! Meanwhile I searched among SO questions and answers and found out this one: https://stackoverflow.com/questions/9193603/applying-a-coloured-overlay-to-an-image-in-either-pil-or-imagemagik The first answer gives an acceptable solution illustrated via scikit image. It seems to be somehow related with alpha blending (alpha composite). After this weekend I'll check it out and let you know my conclusion.

**Comment by empet** [comment]
Indeed, the two successive `imshow`(s) from your code perform the alpha-blending of two images.  Here is the illustration:
[https://nbviewer.jupyter.org/github/empet/alpha-blending/blob/main/alpha-blending-of-two-images.ipynb](https://nbviewer.jupyter.org/github/empet/alpha-blending/blob/main/alpha-blending-of-two-images.ipynb).
But I'm still wondering how and where  is implemented alpha-blending in matplotlib.
